"""Defines the contract strings for the AMM contracts."""


class AMMPoolStrings:
    """AMM Pool contract strings."""

    admin = "a"
    asset1_id = "a1"
    asset1_reserve = "a1r"
    asset2_id = "a2"
    asset2_reserve = "a2r"
    asset_1_to_asset_2_exchange = "e"
    balance_1 = "b1"
    balance_2 = "b2"
    burn_asset1_out = "ba1o"
    burn_asset2_out = "ba2o"
    cumsum_fees_asset1 = "cf1"
    cumsum_fees_asset2 = "cf2"
    cumsum_time_weighted_asset1_to_asset2_price = "ct12"
    cumsum_time_weighted_asset2_to_asset1_price = "ct21"
    cumsum_volume_asset1 = "cv1"
    cumsum_volume_asset2 = "cv2"
    cumsum_volume_weighted_asset1_to_asset2_price = "cv12"
    cumsum_volume_weighted_asset2_to_asset1_price = "cv21"
    flash_loan = "fl"
    flash_loan_fee = "flf"
    future_amplification_factor = "faf"
    future_amplification_factor_time = "fat"
    increase_param_update_delay = "ipu"
    initial_amplification_factor = "iaf"
    initial_amplification_factor_time = "iat"
    initialize_pool = "ip"
    initialized = "i"
    latest_time = "lt"
    lp_circulation = "lc"
    lp_id = "l"
    manager = "m"
    manager_app_id_var = "ma"
    max_flash_loan_ratio = "mflr"
    next_swap_fee_pct_scaled = "nsfp"
    opt_into_assets = "o"
    param_update_delay = "pu"
    pool = "p"
    ramp_amplification_factor = "raf"
    redeem_pool_asset1_residual = "rpa1r"
    redeem_pool_asset2_residual = "rpa2r"
    redeem_swap_residual = "rsr"
    remove_reserves = "rr"
    reserve_factor = "rf"
    schedule_swap_fee_update = "ssf"
    swap_exact_for = "sef"
    swap_fee_pct_scaled_var = "sfp"
    swap_fee_update_time = "sft"
    swap_for_exact = "sfe"
    update_swap_fee = "usf"
    validator_index = "vi"


class AMMManagerStrings:
    """AMM Manager contract strings."""

    admin = "a"
    farm_ops = "fo"
    flash_loan_fee = "flf"
    initialize_pool = "ip"
    max_flash_loan_ratio = "mflr"
    pool_hash_prefix = "ph_"
    registered_asset_1_id = "a1"
    registered_asset_2_id = "a2"
    registered_pool_id = "p"
    reserve_factor = "rf"
    set_flash_loan_fee = "sflf"
    set_max_flash_loan_ratio = "smflr"
    set_reserve_factor = "srf"
    set_validator = "sv"
    validator_index = "vi"
