"""Strings for the staking contract.""" ""


class StakingStrings:
    """A class containing strings for the staking contract."""

    asset_id = "ai"
    boost_multiplier = "lm"
    boost_multiplier_app_id = "bmai"
    claim_rewards = "cr"
    dao_address = "da"
    emergency_dao_address = "eda"
    external_boost_multiplier = "bm"
    farm_ops = "fo"
    initialize_rewards_escrow_account = "irea"
    latest_time = "lt"
    opt_into_asset = "oia"
    reclaim_rewards_assets = "rra"
    rewards_asset_id_prefix = "rai_"
    rewards_coefficient_prefix = "rc_"
    rewards_escrow_account = "rea"
    rewards_issued_prefix = "ri_"
    rewards_paid_prefix = "rp_"
    rewards_per_second_prefix = "rps_"
    rewards_program_count = "rpc"
    rewards_program_counter_prefix = "rpc_"
    rps_pusher = "rpsp"
    scaled_total_staked = "sts"
    set_rewards_program = "srp"
    set_rps_pusher = "srpsp"
    set_voting_escrow_app_id = "sveai"
    stake = "s"
    total_staked = "ts"
    units_staked = "us"
    unstake = "u"
    update_boost_multiplier = "ulm"
    update_rewards_per_second = "urps"
    update_target_user = "utu"
    user_rewards_coefficient_prefix = "urc_"
    user_rewards_program_counter_prefix = "urpc_"
    user_scaled_total_staked = "usts"
    user_total_staked = "uts"
    user_unclaimed_rewards_prefix = "uur_"
    voting_escrow_app_id = "veai"
